name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Upload .env file
        env:
          ENV: ${{ secrets.ENV }}
        run: echo $ENV | base64 --decode > .env
      - name: Install dependencies
        run: npm ci
      - name: Build the app
        run: npx prisma generate && npm run build
      # - name: Install Playwright Browsers
      #   run: npx playwright install --with-deps
      - name: Setup Docker
        run: sudo docker run --network=\host\ --rm --init -it mcr.microsoft.com/playwright:v1.40.1-jammy /bin/sh -c "cd /home/pwuser && npx -y playwright@1.40.1 run-server --port 4422"
      - name: Run Playwright tests
        run: PW_TEST_CONNECT_WS_ENDPOINT=ws://127.0.0.1:4422/ npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
